(defun color-theme-tango ()
  "A color theme based on Tango Palette."
  (interactive)
  (color-theme-install
   '(color-theme-tango
     ((background-color . "#2e3436")
      (border-color . "#888a85")
      (cursor-color . "#729fcf")
      (foreground-color . "#eeeeee")
      (mouse-color . "#8ae234")
      (background-mode . dark))
     ((help-highlight-face . underline)
      (ibuffer-dired-buffer-face . font-lock-function-name-face)
      (ibuffer-help-buffer-face . font-lock-comment-face)
      (ibuffer-hidden-buffer-face . font-lock-warning-face)
      (ibuffer-occur-match-face . font-lock-warning-face)
      (ibuffer-read-only-buffer-face . font-lock-type-face)
      (ibuffer-special-buffer-face . font-lock-keyword-face)
      (ibuffer-title-face . font-lock-type-face))
     (border ((t (:background "#888a85"))))
     (fringe ((t (:background "grey10"))))
     (mode-line ((t (:foreground "#eeeeec" :background "#555753" :box nil))))
     (region ((t (:background "#555753"))))
     (font-lock-builtin-face ((t (:foreground "#729fcf"))))
     (font-lock-comment-face ((t (:foreground "#888a85"))))
     (font-lock-constant-face ((t (:foreground "#8ae234"))))
     (font-lock-doc-face ((t (:foreground "#888a85"))))
     (font-lock-keyword-face ((t (:foreground "#729fcf" :bold t))))
     (font-lock-string-face ((t (:foreground "#ad7fa8" ))))
     (font-lock-type-face ((t (:foreground "#8ae234" :bold t))))
     (font-lock-variable-name-face ((t (:foreground "#fcaf3e"))))
     (cperl-array-face ((t (:foreground "#f57900" ))))
     (cperl-hash-face ((t (:foreground "#c17d11" ))))
     (font-lock-warning-face ((t (:bold t :foreground "#f57900"))))
     (font-lock-function-name-face ((t (:foreground "#edd400" :bold t ))))
     (comint-highlight-input ((t ( :bold t))))
     (comint-highlight-prompt ((t (:foreground "#8ae234"))))
     (isearch ((t (:background "#f57900" :foreground "#2e3436"))))
     (isearch-lazy-highlight-face ((t (:foreground "#2e3436" :background "#e9b96e"))))
     (show-paren-match-face ((t (:foreground "#888a85" :background "#2e3436"))))
     (show-paren-mismatch-face ((t (:background "#ad7fa8" :foreground "#2e3436"))))
     (minibuffer-prompt ((t (:foreground "#729fcf" :bold t))))
     (info-xref ((t (:foreground "#729fcf"))))
     (info-xref-visited ((t (:foreground "#ad7fa8"))))
     (custom-link (( t (:underline t :foreground "#729fcf"))))
     (org-link (( t (:underline t :foreground "#729fcf"))))
	 (hl-line (( t (:background "#444"))))
	 (ido-first-match ((t (:foreground "#ad7fa8" :bold t))))
	 (ido-only-match ((((class color)) (:foreground "#73d216" :bold t))))
	 (ido-subdir ((((min-colors 88) (class color)) (:foreground "#729fcf"))))
	 (py-XXX-tag-face ((t (:foreground "Firebrick"))) t)
	 (py-builtins-face ((t (:foreground "#fcaf3e"))) t)
	 (py-pseudo-keyword-face ((t (:foreground "#8ae234"))) t)
	 (font-lock-function-name-face ((t (:foreground "#edd400" :weight bold))))
     )))

(provide 'color-theme-tango)
